### ISSUE TITLE
google搜尋框輸入文字的時侯不斷出現陰影閃跳

### ISSUE THREAD

**Issue by tomyan112** [syhyz1990/mactype#1]
![image](https://user-images.githubusercontent.com/9064351/76321510-15d98600-631d-11ea-9534-81f666fa07c3.png)
![image](https://user-images.githubusercontent.com/9064351/76321577-30136400-631d-11ea-842a-b7db16e3fbae.png)

**Comment by syhyz1990** [comment]
这个有可能是单词拼错的问题

**Comment by tomyan112** [comment]
> 这个有可能是单词拼错的问题

我剛剛試了, 真的是呢!
