### ISSUE TITLE
没有设置按钮

### ISSUE THREAD

**Issue by enciwojietuo** [syhyz1990/mactype#10]
<img width="253" alt="微信图片_20210418100030" src="https://user-images.githubusercontent.com/65491794/115131765-161e7780-a02d-11eb-9d99-9869a5c611bf.png">

**Comment by huhsiaojung666** [comment]
火狐中有设置按钮~chrome中我也和你一样

**Comment by syhyz1990** [comment]
降级Tampermonkey到上一个版本，最新版的Tampermonkey有Bug
