### ISSUE TITLE
请问该脚本会收集个人浏览记录吗

### ISSUE THREAD

**Issue by SunnyLimc** [syhyz1990/mactype#14]
在脚本中看到如下代码
`// @require           https://js.users.51.la/21053225.js`

**Comment by syhyz1990** [comment]
只能统计使用人数，其他的不会



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年6月20日(周日) 下午4:24
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [syhyz1990/mactype] 请问该脚本会收集个人浏览记录吗 (#14)




 
在脚本中看到如下代码
 // @require           https://js.users.51.la/21053225.js
