### ISSUE TITLE
原理是基于什么呢？

### ISSUE THREAD

**Issue by Crystal-RainSlide** [syhyz1990/mactype#2]
另外，加透明的文字阴影是否有效？

**Comment by StoneForests** [comment]
感觉这个在高分屏下起了反作用，字体边缘有点发虚，不知道是不是windows的原因。。我的电脑T470p，14寸2K分辨率开了150%放大

不开的效果
![image](https://user-images.githubusercontent.com/5436513/77732009-fb065180-703e-11ea-85ff-6dce1f6a789d.png)


开了的效果
![image](https://user-images.githubusercontent.com/5436513/77731965-e5912780-703e-11ea-9483-bad7e4e54d16.png)

**Comment by syhyz1990** [comment]
@Crystal-RainSlide 更新到2.0版本试下
