### ISSUE TITLE
quicker软件会有乱码 望修复这个问题 在进程中也找不到

### ISSUE THREAD

**Issue by ChenZ0814** [syhyz1990/mactype#20]
[https://pan.i95cloud.com/s/5VAIy](url)

**Comment by ChenZ0814** [comment]
https://pan.i95cloud.com/s/5VAIy

**Comment by ChenZ0814** [comment]
https://pan.i95cloud.com/s/JRzH0

**Comment by syhyz1990** [comment]
@ChenZ0814 exe版本的库在这里 https://github.com/snowie2000/mactype，这个是网页版
