### ISSUE TITLE
不知為何 在我這裏 完全失效

### ISSUE THREAD

**Issue by tkp206093** [syhyz1990/mactype#21]
Google Chrome
98.0.4758.102

Tampermonkey BETA
4.14.6152

Mactype助手
2.2.0

以前一拖動 就立刻看見變化
現在怎樣開啟 怎樣拖動 開關 刷新 都完全沒有任何變化

**Comment by syhyz1990** [comment]
删除重装试一下，我试了Tampermonkey BETA + Google Chrome 98.0.4758.102是正常的

**Comment by tkp206093** [comment]
剷除重裝 只有第一次是正常 刷新之後 所有網頁就失效了

**Comment by tkp206093** [comment]
![image](https://user-images.githubusercontent.com/29872453/156445973-62ff5bc2-4812-4b13-842f-f141d31e0c3f.png)
更改執行順序 並不再是預設 就可以確保 腳本順利執行
