### ISSUE TITLE
在普通字体尺寸下有重影，放大到125%才看不见

### ISSUE THREAD

**Issue by OrochiZ** [syhyz1990/mactype#22]
![temp](https://user-images.githubusercontent.com/1974913/158015925-0bce9512-f420-4393-8115-f5ffa1a90d94.PNG)
![temp2](https://user-images.githubusercontent.com/1974913/158015954-def74054-d980-43ed-a90c-c8fc6c31522b.PNG)
这是宋体吧，强制成雅黑试了下，要到150%才能正常

看起来要大于一定字号才能正常

把最小字号设置成15凑合了，页面有点挤

**Comment by syhyz1990** [comment]
调节清晰度，我看了下淘宝是正常的，也是宋体
