### ISSUE TITLE
mactype自己之前可用，重装系统后未生效

### ISSUE THREAD

**Issue by lovobin** [syhyz1990/mactype#24]
重装的win10 清晰度没有变化，浏览器为最新版谷歌浏览器

**Comment by syhyz1990** [comment]
调节清晰度，观察控制台是否有报错

**Comment by lovobin** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "syhyz1990/mactype"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月15日(星期二) 凌晨2:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [syhyz1990/mactype] mactype自己之前可用，重装系统后未生效 (Issue #24)





 
调节清晰度，观察控制台是否有报错
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
