### ISSUE TITLE
能否一次设定所有网站的字体清晰度

### ISSUE THREAD

**Issue by TCDTH** [syhyz1990/mactype#25]
能否一次设定所有网站的字体清晰度，手机X浏览器每打开一个网站都会弹出清晰度设置框，能一次性设置就更方便了

**Comment by syhyz1990** [comment]
电脑上是可以的，手机推荐使用kiwi或者狐猴浏览器



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月19日(周六) 下午5:10
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [syhyz1990/mactype] 能否一次设定所有网站的字体清晰度 (Issue #25)




 
能否一次设定所有网站的字体清晰度，手机X浏览器每打开一个网站都会弹出清晰度设置框，能一次性设置就更方便了
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
