### ISSUE TITLE
有重影

### ISSUE THREAD

**Issue by Baikeryoyo** [syhyz1990/mactype#26]
设置清晰度大于0.1的时候，字体会有重影
![image](https://user-images.githubusercontent.com/57838797/162657450-feb424f7-4825-46b2-a7af-1eeec8722d5b.png)

**Comment by Baikeryoyo** [comment]
测试了一下，XHei 字体的重影会比较严重，默认的微软雅黑重影会轻一点

**Comment by Baikeryoyo** [comment]
看到前面有人发125%重影就会消失，测了一下，不开启脚本网页缩放到125%也是很清晰的，修改清晰度在3以内基本没变化
网页缩放125%相当于开启脚本后清晰度2左右

**Comment by Baikeryoyo** [comment]
这样的情况下，我在浏览网页的时候，手动CTRL+鼠标滚轮进行网页缩放，会不会更加方便一点

**Comment by Baikeryoyo** [comment]
这样的情况下，我在浏览器设置修改默认缩放为125%，会不会更加方便一点，或者在有需要的时候，使用CTRL+鼠标滚轮调节缩放

**Comment by Cenc-sy** [comment]
![image](https://user-images.githubusercontent.com/65340011/168205744-58f3ded8-71f9-441f-8f57-507d0eaff55a.png)
根据公众号下载后，我的matlab乱码了
![image](https://user-images.githubusercontent.com/65340011/168205889-a867f946-466e-4c20-9bd0-ab447c63fb82.png)

**Comment by Cenc-sy** [comment]
您好，我已收到您的邮件。
