### ISSUE TITLE
请问可以提供下历史版本么？

### ISSUE THREAD

**Issue by fallsong** [syhyz1990/mactype#4]
最新版在谷歌上显示效果怪怪的，能提供下之前不能设置字体清晰度的版本么？

**Comment by PhilosophyBuns** [comment]
同问，最新版显示的问题很大用不了，需要历史版本

**Comment by leyan22** [comment]
2.0.1版本好像确实有问题，我在华为和荣耀商城造成无法登录！关闭脚本后登录再启用脚本，登录又失效！

**Comment by iwoorst** [comment]
需要+1  新版本感觉没以前好

**Comment by ZaiDAP** [comment]
新版本改成描边了，不如之前的阴影效果好。
贴一下以前的，Shadow 值我改过了，可以自己修改到感觉适合的值
`// ==UserScript==
// @name              Mactype助手老版本效果好
// @namespace         https://github.com/syhyz1990/mactype
// @version           1.0.0
// @icon              https://www.baiduyun.wiki/mactype.png
// @description       配合 Mactype 实现Chrome，Edge等不支持关闭 DirectWrite 浏览器的字体渲染支持
// @author            syhyz1990
// @license           MIT
// @supportURL        https://github.com/syhyz1990/mactype
// @updateURL         https://www.baiduyun.wiki/mactype.user.js
// @downloadURL       https://www.baiduyun.wiki/mactype.user.js
// @match             *://*/*
// @run-at            document-start
// @grant             GM_addStyle
// ==/UserScript==

(function () {
  'use strict'
  GM_addStyle(`
    body,input,textarea {
        text-shadow: 0px 0px .5px #333333;
    }
`)
})()
`

**Comment by syhyz1990** [comment]
之前的可以从这里安装

https://github.com/syhyz1990/mactype/raw/2eceac6243cb64dccfa51407da442ab7a4828fc8/mactype.user.js

**Comment by leyan22** [comment]
https://www.hihonor.com/cn/shop

**Comment by leyan22** [comment]
https://www.hihonor.com/cn/shop 这个网站2.0.4版本 仍然无法登录，就算选择该网站不启用，也不行，禁用本脚本即可以登录。

**Comment by syhyz1990** [comment]
@leyan22 加上这一句

// @exclude           *://*.hihonor.com/*

![image](https://user-images.githubusercontent.com/5344173/107120159-ec2b3500-68c6-11eb-92d0-f4a3327cfd19.png)
