### ISSUE TITLE
在百度搜索栏搜索其他内容后失效，必须刷新

### ISSUE THREAD

**Issue by NightWatch0** [syhyz1990/mactype#5]
百度搜索框里输入其他东西并搜索后会失效。

希望可以提供个Stylus版本的，它应该就没这种问题。

**Comment by NightWatch0** [comment]
顺便补充下被选中的文字看起来有点怪

**Comment by NightWatch0** [comment]
请问CSS样式这样写对嘛？

@namespace url(http://www.w3.org/1999/xhtml);
body,input,textarea,keygen,select,button,.navigator-toolbox,.toolbarbutton-text,.sidebar-title{
-webkit-text-stroke: 0.3px !important;
}

**Comment by syhyz1990** [comment]
Stylus不支持设置，值只能定死。搜索问题下版本解决


---原始邮件---
发件人: &quot;NightWatch0&quot;<notifications@github.com&gt;
发送时间: 2021年1月31日(周日) 晚上10:18
收件人: &quot;syhyz1990/mactype&quot;<mactype@noreply.github.com&gt;;
抄送: &quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题: [syhyz1990/mactype] 在百度搜索栏搜索其他内容后失效，必须刷新 (#5)




 
百度搜索框里输入其他东西并搜索后会失效。
 
希望可以提供个Stylus版本的，它应该就没这种问题。
 
&mdash;

**Comment by syhyz1990** [comment]
@NightWatch0 2.0.2 已经解决了
